NS_Custom_Parks = [
    'Neurosen-Strand'
    'Profi-Spot-Check'
    'Lavapark'
    'DDT 2'
    'Das Labor'
    'Tal des Todes 2'
    'Toodles'
    'Trailer-Attraktion'
    '8uN9h013'
    '100 Großer Park'
    'Lines-Park'
    'Slap-o-manie'
    'Pool-Paradies'
    'Railfabrik'
    'Land unter'
    'Chicken Fun 2'
    'Mach mir den Hengst'
    'Liebesgrotte'
    'Beach-Contest'
    'Ausgrabungsstätte'
]
