NS_Custom_Parks = [
    'Neurotyczna pla¿a'
    'Sprawdzian miejscówki zawodowców'
    'Park wulkaniczny'
    'DDT 2'
    'Laboratorium skillsów'
    'Dó³ mierci 2'
    'Toodles'
    'Przeci¹ganie przyczepy'
    '8uN9h013'
    'Du¿y park \'100\''
    'Park \'lines\' z IC'
    'Labirynt plaskaczy'
    'Basenowy raj'
    'Fabryka szyn'
    'Ji-Land'
    'Kojec kurczaka 2'
    'Dzika jazda ogiera'
    'Mi³osna grota Glenna'
    'Pla¿owy konkurs Fonga'
    'Wykopaliska Noela'
]
